"""3 update domain

Revision ID: 7417b0a648c8
Revises: 6ebdb93574f6
Create Date: 2025-04-28 13:03:15.458093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7417b0a648c8'
down_revision: Union[str, None] = '6ebdb93574f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org', sa.Column('domain', sa.String(), nullable=True))
    op.drop_column('org', 'domains')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org', sa.Column('domains', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('org', 'domain')
    # ### end Alembic commands ###
